//! Embedded provider brand icons for the serve web dashboard.
//!
//! Upstream parity (A3, #2722): icons are served from an embedded `/icons/`
//! route as static brand art — no account data, so no auth; immutable per
//! binary, so aggressively cacheable (`Cache-Control: public, max-age=86400,
//! immutable`, upstream's exact policy). Assets are the pinned upstream SVGs
//! (`upstream v0.48.0: Sources/CodexBar/Resources/ProviderIcon-*.svg`), embedded
//! with `include_bytes!` so the CLI ships as a standalone binary, mirroring
//! upstream's reason for embedding (`CLIServeProviderIcons`).
//! Upstream regenerates its table with `Scripts/generate_serve_provider_icons.py`;
//! this file is regenerated by copying the resources from the upstream tag.

/// Resource name embedded in this binary for `row_id` (a local provider
/// `cli_name`), with dash-normalization for ids that differ from upstream
/// resource naming (`qwen-cloud` → `ProviderIcon-qwencloud`).
/// Unknown names — including pathological ones — yield `None` → 404.
pub fn icon_resource_for(row_id: &str) -> Option<&'static str> {
    let direct = format!("ProviderIcon-{row_id}");
    let normalized = format!("ProviderIcon-{}", row_id.replace('-', ""));
    ICONS
        .binary_search_by_key(&direct.as_str(), |(name, _)| name)
        .or_else(|_| ICONS.binary_search_by_key(&normalized.as_str(), |(name, _)| name))
        .ok()
        .map(|index| ICONS[index].0)
}

/// Look up an embedded icon by resource name (without `.svg`).
/// Unknown names — including pathological ones — yield `None` → 404.
pub fn icon_bytes(resource_name: &str) -> Option<&'static [u8]> {
    ICONS
        .binary_search_by_key(&resource_name, |(name, _)| name)
        .ok()
        .map(|index| ICONS[index].1)
}

/// Local provider-id → icon URL map injected into the page (keys sorted for
/// deterministic, greppable HTML — upstream parity). Only providers whose icon
/// is actually embedded appear; the UI falls back to a neutral dot. Keyed by
/// LOCAL `cli_name`s, so every referenced icon resolves and no dead provider
/// ids leak in.
pub fn icon_url_map() -> String {
    let mut ids: Vec<&str> = crate::core::cli_name_map().keys().copied().collect();
    ids.sort_unstable();
    let mut out = String::from("{");
    let mut first = true;
    for id in ids {
        let Some(resource) = icon_resource_for(id) else {
            continue;
        };
        if !first {
            out.push(',');
        }
        first = false;
        out.push_str(&serde_json::to_string(id).unwrap_or_default());
        out.push(':');
        out.push_str(&serde_json::to_string(&format!("/icons/{resource}.svg")).unwrap_or_default());
    }
    out.push('}');
    out
}

/// Embeds `icons/ProviderIcon-<name>.svg` under `ProviderIcon-<name>`.
macro_rules! icons {
    ($($name:literal),* $(,)?) => {
        &[$((
            concat!("ProviderIcon-", $name),
            include_bytes!(concat!("icons/ProviderIcon-", $name, ".svg")),
        )),*]
    };
}

/// Sorted static table (enables binary search). Keep in ASCII order.
static ICONS: &[(&str, &[u8])] = icons![
    "abacus",
    "aiand",
    "alibaba",
    "amp",
    "antigravity",
    "augment",
    "bedrock",
    "chutes",
    "claude",
    "clinepass",
    "codebuff",
    "coderabbit",
    "codex",
    "commandcode",
    "copilot",
    "cursor",
    "deepgram",
    "deepinfra",
    "deepseek",
    "devin",
    "devpass",
    "doubao",
    "elevenlabs",
    "factory",
    "gemini",
    "grok",
    "groq",
    "huggingface",
    "jetbrains",
    "kilo",
    "kimi",
    "kiro",
    "litellm",
    "llmman",
    "llmproxy",
    "longcat",
    "manus",
    "mimo",
    "minimax",
    "mistral",
    "muse",
    "neuralwatt",
    "notion",
    "nous",
    "ollama",
    "opencode",
    "opencodego",
    "openrouter",
    "perplexity",
    "poe",
    "qoder",
    "qwencloud",
    "raycast",
    "replicate",
    "sakana",
    "stepfun",
    "sub2api",
    "t3chat",
    "venice",
    "vertexai",
    "warp",
    "wayfinder",
    "windsurf",
    "xai",
    "xkiro",
    "zai",
    "zed",
    "zenmux",
    "zoommate",
];

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn icon_table_embeds_every_svg_in_the_icons_dir() {
        let dir =
            std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("src/cli/serve/dashboard/icons");
        let mut on_disk: Vec<String> = std::fs::read_dir(&dir)
            .unwrap()
            .map(|entry| entry.unwrap().file_name().to_string_lossy().into_owned())
            .collect();
        on_disk.sort();
        let embedded: Vec<String> = ICONS
            .iter()
            .map(|(name, _)| format!("{name}.svg"))
            .collect();
        assert_eq!(embedded, on_disk);
        assert_eq!(ICONS.len(), 69);
        for (name, bytes) in ICONS {
            let expected = std::fs::read(dir.join(format!("{name}.svg"))).unwrap();
            assert_eq!(*bytes, expected.as_slice(), "{name}");
        }
    }

    #[test]
    fn icon_table_is_sorted_for_binary_search() {
        let mut sorted = ICONS.iter().map(|(name, _)| *name).collect::<Vec<_>>();
        let original = sorted.clone();
        sorted.sort_unstable();
        assert_eq!(original, sorted, "static table must stay ASCII-sorted");
    }

    #[test]
    fn all_icons_are_valid_utf8_svg() {
        for (name, bytes) in ICONS {
            let text = std::str::from_utf8(bytes).unwrap_or_else(|e| panic!("{name}:{e}"));
            assert!(text.contains("<svg"), "{name}: must be svg markup");
        }
    }

    #[test]
    fn known_icons_are_valid_svg() {
        let bytes = icon_bytes("ProviderIcon-codex").expect("codex icon embedded");
        let text = std::str::from_utf8(bytes).expect("icons are utf-8 svg");
        assert!(text.contains("<svg"), "must be svg markup");
    }

    #[test]
    fn unknown_and_pathological_names_miss() {
        assert!(icon_bytes("ProviderIcon-nope").is_none());
        assert!(icon_bytes("../etc/passwd").is_none());
        assert!(icon_bytes("ProviderIcon-codex.svg").is_none());
        assert!(icon_bytes("").is_none());
    }

    #[test]
    fn icon_url_map_is_sorted_json_of_embedded_only() {
        let map: serde_json::Value = serde_json::from_str(&icon_url_map()).unwrap();
        let obj = map.as_object().unwrap();
        assert_eq!(obj.get("codex").unwrap(), "/icons/ProviderIcon-codex.svg");
        assert_eq!(obj.get("claude").unwrap(), "/icons/ProviderIcon-claude.svg");
        // Dash-normalized local id → upstream resource name.
        assert_eq!(
            obj.get("qwen-cloud").unwrap(),
            "/icons/ProviderIcon-qwencloud.svg"
        );
        assert!(obj.get("openaiapi").is_none(), "no asset -> no entry");
        assert!(obj.get("clawrouter").is_none(), "no such local provider");
        assert!(obj.get("synthetic").is_none(), "no such local provider");
        let keys: Vec<&String> = obj.keys().collect();
        let mut sorted = keys.clone();
        sorted.sort();
        assert_eq!(keys, sorted, "deterministic sorted output");
        // Every mapped key is a real local provider id reachable via the CLI.
        for key in obj.keys() {
            assert!(
                crate::core::cli_name_map().contains_key(key.as_str()),
                "dead provider id leaked into icon map: {key}"
            );
        }
    }

    #[test]
    fn icon_resource_for_normalizes_dash_ids() {
        assert_eq!(
            icon_resource_for("qwen-cloud"),
            Some("ProviderIcon-qwencloud")
        );
        assert_eq!(icon_resource_for("codex"), Some("ProviderIcon-codex"));
        assert!(icon_resource_for("clawrouter").is_none());
        assert!(icon_resource_for("../etc").is_none());
    }
}
